security:
   encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
   
   providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
   firewalls:
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            remember_me:
              key: "%secret%"
              lifetime: 30000000000
              path: /
              domain: ~
            logout:       true
            anonymous:    true