services:
  manu.twig.asgtt_extension:
        class: Manu\AsgttBundle\Twig\ASGTTExtension
        arguments:  ["@request_stack","@service_container"]
        tags:
            - { name: twig.extension }
            
  articles_manager:
        class: Manu\AsgttBundle\Managers\ArticlesManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  managers_manager:
        class: Manu\AsgttBundle\Managers\ManagersManager
        arguments: ["@doctrine", "@templating", "@logger", "@service_container"]
        
  doi_manager:
        class: Manu\AsgttBundle\Managers\DOIManager
        arguments: ["@service_container",  "@doctrine", "@templating", "@logger"]
    
  liste_manager:
        class: Manu\AsgttBundle\Managers\ListeManager
        arguments: ["@doctrine", "@templating", "@logger", "@service_container"]
    
  reporting_manager:
        class: Manu\AsgttBundle\Managers\ReportingManager
        arguments: ["@doctrine", "@templating", "@logger", "@service_container"]
        
  configuration_liste_manager:
        class: Manu\AsgttBundle\Managers\ConfigurationListeManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
        
  users_manager:
        class: Manu\AsgttBundle\Managers\UsersManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  adresses_manager:
        class: Manu\AsgttBundle\Managers\AdressesManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  categories_manager:
        class: Manu\AsgttBundle\Managers\CategoriesManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  joueurs_manager:
        class: Manu\AsgttBundle\Managers\JoueursManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  admins_manager:
        class: Manu\AsgttBundle\Managers\AdministratorsManager
        arguments: ["@doctrine", "@logger", "@service_container"]
  
  pages_manager:
        class: Manu\AsgttBundle\Managers\PagesManager
        arguments: ["@doctrine", "@logger", "@service_container"]
        
  security_manager:
        class: Manu\AsgttBundle\Managers\SecurityManager
        arguments: ["@service_container", "@doctrine", "@templating", "@logger"]